# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Jenkins Server
  config.vm.define "jenkins_server" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "jenkins-server"

    server.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9462", ip: "192.168.31.145", hostname: true
    server.vm.network "private_network", ip: "192.168.40.11", virtualbox__intnet: true

    server.vm.network "forwarded_port", guest: 8080, host: 8080

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "jenkins_server"
            
      vb.cpus = 1
      vb.memory = "1024"
    end
  
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y && sudo apt upgrade -y
      sudo apt install fontconfig openjdk-17-jre ca-certificates curl -y

      # Install docker for install script
      sudo /bin/bash /vagrant/init_script/install_docker.sh

      # Install jenkins server
      sudo /bin/bash /vagrant/init_script/install_jenkins.sh

    SHELL
  end
  
  # Jenkins Worker
  config.vm.define "jenkins_worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "jenkins-worker"

    worker.vm.network "private_network", ip: "192.168.40.12", virtualbox__intnet: true
  
    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "jenkins_worker"
        
      vb.cpus = 1
      vb.memory = "2048"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y && sudo apt upgrade -y
      sudo apt install fontconfig openjdk-17-jre ca-certificates curl -y

      # Install docker for install script
      sudo /bin/bash /vagrant/init_script/install_docker.sh

      sudo adduser --group --home /home/jenkins --shell /bin/bash jenkins
    SHELL
  end
end