version: '3.7'

services:
  node-app:
    image: node:14
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app 
    command: ["npm", "start"] 
    ports:
      - "3000:3000"

  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf 
      - /var/log:/var/log  
    environment:
      - FLUENTD_CONF=fluentd.conf
    ports:
      - "24224:24224" 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  
      - "9300:9300"  

 
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local
