services:
  elasticsearch:
    image: elasticsearch:8.16.0
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    ports:
       - 9200:9200  
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - homework

  fluentd:
    image: fluentd:latest
    build:
      context: ./
      dockerfile: ./Dockerfile_fluentd
    volumes:
       - ./fluentd/conf:/fluentd/etc
       - ./logs:/fluentd/log
    ports:
      - 24224:24224/udp
    networks:
      - homework
  
  kibana:
    image: kibana:8.16.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - homework

  application:
    image: homework:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
    networks:
      - homework

volumes:
  elastic:

networks:
  homework:
    driver: bridge